project_id: '554061'
api_token: 'CROWDIN_PERSONAL_TOKEN'
base_path: '/root/docs'
preserve_hierarchy: true
files:
  # Docs Markdown files
  - source: /docs/threatmapper/**/*
    dest: /threatmapper/**/%original_file_name%
    #translation: /i18n/%locale%/docusaurus-plugin-content-docs/current/threatmapper/**/%original_file_name%
    translation: /%locale%/threatmapper/**/%original_file_name%
